config/routes.rb
IcandothatSignmeup::Application.routes.draw do
  resources :events
  resources :commitments

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show, :index]

  match "/home/index" => "home#index"
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :commitments
  has_many :users, :through => :commitments

  attr_accessible :commitment_type, :description, :end_time, :location, :max_volunteers, :min_volunteers, :start_time, :title
  
  # need to override the json view to return what full_calendar is expecting.
  # http://arshaw.com/fullcalendar/docs/event_data/Event_Object/
  def as_json(options = {})
    {
      :id => self.id,
      :title => self.title,
      :description => self.description || "",
      :start => start_time.rfc822,
      :end => end_time.rfc822,
      :allDay => false,
      :recurring => false,
      :color => self.event_status,
      :textColor => 'black',
      :url => Rails.application.routes.url_helpers.event_path(id)
    }
  end
  
  def self.format_date(date_time)
    Time.at(date_time.to_i).to_formatted_s(:db)
  end

  def event_status
    unless User.current_user.nil?
      commitment = User.current_user.commitments.find_by_event_id(self.id)
      unless commitment.nil?
        if commitment.status == 'OFFERED'
          '#FFFF84'
        elsif commitment.status == 'ACCEPTED'
          '#BEFEEB'
        elsif commitment.status == 'COMMITTED'
          '#B3FF99'
        end
      else
        commitment_count = Commitment.where(:event_id => self.id, :status => 'COMMITTED').length
        if commitment_count >= self.max_volunteers
          '#FF9797'
        else
          '#F5F0DD'
        end
      end
    else
      'red'
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    User.current_user = current_user

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
      format.js
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @commitment = current_user.commitments.find_by_event_id(@event.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= simple_form_for(@event) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :description
    = f.input :location
    = f.input :start_time
    = f.input :end_time
    = f.input :min_volunteers
    = f.input :max_volunteers
    = f.input :commitment_type

  .form-actions
    = f.button :submit

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
%h1 Listing events

%table
  %tr
    %th Title
    %th Description
    %th Location
    %th Start time
    %th End time
    %th Min volunteers
    %th Max volunteers
    %th Commitment type
    %th
    %th
    %th

  - @events.each do |event|
    %tr
      %td= event.title
      %td= event.description
      %td= event.location
      %td= event.start_time
      %td= event.end_time
      %td= event.min_volunteers
      %td= event.max_volunteers
      %td= event.commitment_type
      %td= link_to 'Show', event
      %td= link_to 'Edit', edit_event_path(event)
      %td= link_to 'Destroy', event, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Event', new_event_path

app/views/events/new.html.haml
%h1 New event

= render 'form'

= link_to 'Back', events_path

app/views/events/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @event.title
%p
  %b Description:
  = @event.description
%p
  %b Location:
  = @event.location
%p
  %b Start time:
  = @event.start_time
%p
  %b End time:
  = @event.end_time
%p
  %b Min volunteers:
  = @event.min_volunteers
%p
  %b Max volunteers:
  = @event.max_volunteers
%p
  %b Commitment type:
  = @event.commitment_type

- if user_signed_in?
  - if @commitment
    %p
      %b Commitment Status
      = @commitment.status
  - else
    = link_to "Volunteer", commitments_path(:event_id => @event.id), :method => :post
                                   
= link_to 'Edit', edit_event_path(@event)
\|
= link_to 'Back', events_path